import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { Lock, ShieldCheck, Eye, Database, HelpCircle } from "lucide-react";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | Krishi Sanjha" },
      {
        name: "description",
        content:
          "Privacy Policy of Krishi Sanjha Technologies Pvt. Ltd. detailing how we collect, use, and protect your personal and agricultural data.",
      },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <AppShell>
      <div className="bg-[#FAF7F1] py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto bg-white rounded-2xl p-8 md:p-12 shadow-xs border border-[#c2c8c1]/40">
          <div className="border-b border-[#c2c8c1]/40 pb-6 mb-8">
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#1f3d2b] mb-2">
              <Lock className="size-4" />
              <span>Data Protection & Privacy · Effective Date: January 1, 2024</span>
            </div>
            <h1 className="font-serif text-3xl sm:text-4xl font-bold text-[#082717]">
              Privacy Policy
            </h1>
            <p className="text-sm text-[#424843] mt-2">
              <strong>Krishi Sanjha Technologies Private Limited</strong> ("Krishi Sanjha", "we", "us", or "our") is dedicated to safeguarding the privacy and security of farmers, equipment owners, and operators.
            </p>
          </div>

          <div className="space-y-8 text-sm sm:text-base text-[#424843] leading-relaxed">
            {/* Section 1 */}
            <section>
              <h2 className="font-serif text-xl font-bold text-[#082717] mb-3 flex items-center gap-2">
                <Database className="size-5 text-[#7b5800]" />
                1. Information We Collect
              </h2>
              <p>
                To provide farm mechanization, match nearby machinery, and process bookings securely, we may collect the following categories of information:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>
                  <strong>Personal Identity Information:</strong> Name, mobile phone number, father's/guardian's name, village, panchayat, and block.
                </li>
                <li>
                  <strong>Verification Data:</strong> Last 4 digits of Aadhaar or Government photo ID for identity validation and anti-fraud verification.
                </li>
                <li>
                  <strong>Agricultural Land Data:</strong> Farm location, plot GPS coordinates, soil characteristics, and plot area measured in local units (Bigha / Katha / Dhur).
                </li>
                <li>
                  <strong>Equipment & Operator Information:</strong> Machine registration papers, implement types, horsepower specifications, and commercial driving license numbers.
                </li>
                <li>
                  <strong>Transaction & Booking Data:</strong> Details of machinery booked, rental duration, invoice amounts, and transaction IDs generated by <strong>Zoho Payments</strong>.
                </li>
              </ul>
            </section>

            {/* Section 2 */}
            <section>
              <h2 className="font-serif text-xl font-bold text-[#082717] mb-3 flex items-center gap-2">
                <Eye className="size-5 text-[#7b5800]" />
                2. How We Use Your Information
              </h2>
              <p>We use the collected information for specific, lawful purposes:</p>
              <ul className="list-disc pl-6 space-y-1.5 mt-2">
                <li>To calculate nearest equipment distance and optimize machine dispatch to your field.</li>
                <li>To authenticate user identity and prevent fraudulent bookings.</li>
                <li>To facilitate communication between farmers, equipment owners, and operators.</li>
                <li>To issue tax invoices and process transactions securely via Zoho Payments.</li>
                <li>To provide customer support and handle grievance redressals.</li>
              </ul>
            </section>

            {/* Section 3 */}
            <section>
              <h2 className="font-serif text-xl font-bold text-[#082717] mb-3 flex items-center gap-2">
                <ShieldCheck className="size-5 text-[#1f3d2b]" />
                3. Payment Information & Security (Zoho Payments)
              </h2>
              <div className="bg-[#f6f3ed] p-5 rounded-xl border border-[#c2c8c1]/40 space-y-2">
                <p>
                  <strong>PCI-DSS Compliant Payment Handling:</strong> Krishi Sanjha does not store sensitive payment card details, bank account passwords, or UPI PINs on its servers.
                </p>
                <p>
                  All online payments are processed through <strong>Zoho Payments</strong>, an RBI-regulated and PCI-DSS Level 1 compliant payment gateway. Transmission of payment data is encrypted using 256-bit Secure Socket Layer (SSL) technology.
                </p>
              </div>
            </section>

            {/* Section 4 */}
            <section>
              <h2 className="font-serif text-xl font-bold text-[#082717] mb-3">
                4. Data Sharing & Disclosure
              </h2>
              <p>
                We do <strong>not</strong> sell, rent, or trade your personal data to third parties for commercial marketing purposes. Data is only shared with:
              </p>
              <ul className="list-disc pl-6 space-y-1.5 mt-2">
                <li><strong>Assigned Equipment Owner / Operator:</strong> Shared only with the respective party to complete the scheduled farm service (e.g. farmer name, phone number, plot location).</li>
                <li><strong>Regulatory / Government Authorities:</strong> When required by applicable Indian laws or lawful court orders.</li>
              </ul>
            </section>

            {/* Section 5 */}
            <section>
              <h2 className="font-serif text-xl font-bold text-[#082717] mb-3">
                5. Data Retention & Your Rights
              </h2>
              <p>
                We retain your account data for as long as your profile remains active. You have the right to request access to your personal details, correct inaccuracies, or request account closure and data deletion by writing to our privacy team.
              </p>
            </section>

            {/* Section 6 */}
            <section className="bg-[#FAF7F1] p-6 rounded-xl border border-[#c2c8c1]/40">
              <h3 className="font-bold text-[#082717] mb-2 flex items-center gap-2">
                <HelpCircle className="size-5 text-[#7b5800]" />
                Privacy & Data Protection Contact
              </h3>
              <p className="text-sm">
                If you have questions or concerns about this Privacy Policy or wish to exercise your data rights, please contact our designated Data Protection Officer:
              </p>
              <p className="text-sm font-semibold text-[#1c1c18] mt-2">
                Data Protection Officer, Krishi Sanjha Technologies Pvt. Ltd.<br />
                Email: <a href="mailto:krishisanjha@gmail.com" className="text-[#7b5800] hover:underline">krishisanjha@gmail.com</a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
